### ISSUE TITLE
'google/maps' is not in the npm registry.

### ISSUE THREAD

**Issue by bogem** [jaebradley/uber-cli#29]
Tried to install it on macOS Sierra, but become this error:
```
(iMac) / sudo npm install uber-cli -g
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'google/maps' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'uber-cli'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 16.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "uber-cli" "-g"
npm ERR! cwd /
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```
Maybe I don't understand something because I haven't got many experience with nodejs earlier.

**Comment by sjs7007** [comment]
At first it seems like the google/mpas module is not published. But as seen [here](https://www.npmjs.com/package/@google/maps), it clearly is. 

Perhaps manually try to install it by running : 

```
npm install @google/maps
```

and then try again. If that doesn't work, [this](https://github.com/googlemaps/google-maps-services-js/issues/50) seems to be a similar issue and in this case it was fixed by updating npm using the following command : 

```
npm install -g npm
```

**Comment by bogem** [comment]
Thank you @sjs7007!
`npm install -g npm` did the trick.

**Comment by sjs7007** [comment]
@bogem Happy to be of help. :)
